# Generated by Django 2.1.4 on 2019-01-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dc_username',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='something',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
