# Generated by Django 2.1.4 on 2019-01-04 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20190103_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(default=None)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyToComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(default=None)),
                ('comment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_comment',
                                   to='blog.Comment')),
            ],
        ),
    ]
