# Generated by Django 2.1.4 on 2019-01-04 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_comment_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='comment_on_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
